events {}

http {
    server { 
        listen 8080;
        server_name frontend;
        absolute_redirect off;
        port_in_redirect off;

        location / {
            root /code/frontend;
            index index.html;
            try_files $uri /index.html;
        }
        
        location /api {
            proxy_pass http://backend:8000;
        }
        
        location /algobattle/api {
            alias /api;
            proxy_pass http://backend:8000;
        }

        location /docs {
            alias /code/docs;
            index index.html;
        }
    include /etc/nginx/mime.types;
    client_max_body_size 2G;
    }
}
