[build-system]
requires = ["uv_build>=0.12.19,<0.13"]
build-backend = "uv_build"

[project]
name = "algobattle_web"
version = "0.18.0"
requires-python = "~=3.14.0"
license = {text = "MIT"}
authors = [{name = "Imogen Hergeth"}, {name = "Henri Lotze"}]
urls = {github = "https://github.com/Algorithmic-Battle/algobattle-web"}
classifiers = [
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Typing :: Typed",
]
dependencies = [
    "algobattle-base==4.3.5",
    "uvicorn~=0.54.0",
    "fastapi~=0.141.1",
    "python-jose[cryptography]~=3.5.0",
    "python-multipart~=0.0.32",
    "sqlalchemy~=2.1.1",
    "pydantic~=2.13.5",
    "pydantic-extra-types~=2.11.1",
    "markdown~=3.11",
    "mysqlclient~=2.3.0",
    "alembic~=1.20.0",
]

[dependency-groups]
dev = [
    "watchfiles~=1.3.0",
]

[project.scripts]
algobattle_api = "algobattle_web.app:create_openapi"
algobattle_runner = "algobattle_web.battle:main"

[tool.uv.build-backend]
module-name = "algobattle_web"

[tool.ruff]
preview = true
line-length = 100
exclude = ["docs/src"]

[tool.ruff.lint]
select = [
    "F",
    "E4",
    "E7",
    "E9",
    "I",
    "UP",
    "YTT",
    "ASYNC",
    "BLE",
    "FBT",
    "B",
    "C4",
    "DTZ",
    "ISC",
    "G",
    "PIE",
    "PYI",
    "SLOT",
    "SIM",
    "PTH",
    "TRY",
    "FLY",
    "PERF",
    "FURB",
    "RUF",
]
ignore = [
    "raise-vanilla-args",
    "unnecessary-placeholder",
    "boolean-type-hint-positional-argument",
    "boolean-default-value-positional-argument",
    "empty-method-without-abstract-decorator",
    "boolean-positional-value-in-call",
    "ambiguous-unicode-character-string",
    "none-not-at-end-of-union",
    "blind-except",
    "call-datetime-now-without-tzinfo",
    "async-function-with-timeout",
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false
combine-as-imports = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pyright]
exclude = [".venv", "docs", "**/node_modules", "**/__pycache__", "**/.*"]
typeCheckingMode = "standard"
disableBytesTypePromotions = true
strictDictionaryInference = true
strictListInference = true
strictSetInference = true
deprecateTypingAliases = true
enableExperimentalFeatures = true
reportAssertAlwaysTrue = "information"
reportUnusedExpression = "information"
reportConstantRedefinition = "warning"
reportDeprecated = "information"
reportDuplicateImport = "information"
reportIncompleteStub = "warning"
reportInconsistentConstructor = "error"
reportInvalidStubStatement = "warning"
reportMatchNotExhaustive = "warning"
reportMissingParameterType = "warning"
reportMissingTypeArgument = "none"
reportPrivateUsage = "none"
reportTypeCommentUsage = "information"
reportUnknownArgumentType = "none"
reportUnknownLambdaType = "none"
reportUnknownMemberType = "none"
reportUnknownParameterType = "warning"
reportUnknownVariableType = "none"
reportUnnecessaryCast = "information"
reportUnnecessaryIsInstance = "information"
reportUnnecessaryComparison = "information"
reportUnnecessaryContains = "information"
reportUnusedCoroutine = "warning"
reportUntypedFunctionDecorator = "warning"
reportUntypedClassDecorator = "warning"
reportUntypedBaseClass = "warning"
reportUntypedNamedTuple = "warning"
reportCallInDefaultInitializer = "none"
reportImportCycles = "warning"
reportPropertyTypeMismatch = "error"
reportShadowedImports = "warning"
reportUnnecessaryTypeIgnoreComment = "information"
reportUninitializedInstanceVariable = "warning"
reportFunctionMemberAccess = "warning"
reportOverlappingOverload = "warning"
